### PR TITLE
Npm updates + bump version to 2.0.0

### PR DESCRIPTION
**Pull request by UniquePanda**
This updates some npm packages and bumps the version of this package to 2.0.0
The version bump should have been done before because we already introduced breaking changes (e.g. no IE support anymore).
After this PR is merged, we'll create a proper tag and release.

I also removed the file `dist/registerPolyfills.d.ts` as this was a left over of the polyfills which were already removed in #2.

The following changes were performed by the npm update. As this package only has dev dependencies, this shouldn't matter for production use.
(I used my npm-with-diff package to get the changelog)
```
source-map-loader
        * Was updated.
        * 3.0.1 => 3.0.2
abab (source-map-loader -> *abab*)
        * Was updated.
        * 2.0.5 => 2.0.6
webpack (source-map-loader -> *webpack*)
        * Was updated.
        * 5.47.0 => 5.75.0
ts-loader
        * Was updated.
        * 9.2.6 => 9.4.2
enhanced-resolve (ts-loader -> *enhanced-resolve*)
        * Was updated.
        * 5.8.2 => 5.12.0
graceful-fs (ts-loader -> enhanced-resolve -> *graceful-fs*)
        * Was updated.
        * 4.2.6 => 4.2.10
tapable (ts-loader -> enhanced-resolve -> *tapable*)
        * Was updated.
        * 2.2.0 => 2.2.1
micromatch (ts-loader -> *micromatch*)
        * Was updated.
        * 4.0.4 => 4.0.5
semver (ts-loader -> *semver*)
        * Was updated.
        * 7.3.5 => 7.3.8
typescript (ts-loader -> *typescript*)
        * Was updated.
        * 4.5.4 => 4.9.5
webpack (ts-loader -> *webpack*)
        * Was updated.
        * 5.47.0 => 5.75.0
webpack-cli
        * Was updated.
        * 4.7.2 => 4.10.0
cross-spawn (webpack-cli -> *cross-spawn*)
        * Was added.
        * Has 3 direct dependencies (not listed here).
@discoveryjs/json-ext (webpack-cli -> *@discoveryjs/json-ext*)
        * Was updated.
        * 0.5.3 => 0.5.7
@webpack-cli/configtest (webpack-cli -> *@webpack-cli/configtest*)
        * Was updated.
        * 1.0.4 => 1.2.0
webpack-cli (webpack-cli -> @webpack-cli/configtest -> *webpack-cli*)
        * Was updated.
        * 4.7.2 => 4.10.0
webpack (webpack-cli -> @webpack-cli/configtest -> *webpack*)
        * Was updated.
        * 5.47.0 => 5.75.0
@webpack-cli/info (webpack-cli -> *@webpack-cli/info*)
        * Was updated.
        * 1.3.0 => 1.5.0
webpack-cli (webpack-cli -> @webpack-cli/info -> *webpack-cli*)
        * Was updated.
        * 4.7.2 => 4.10.0
@webpack-cli/serve (webpack-cli -> *@webpack-cli/serve*)
        * Was updated.
        * 1.5.1 => 1.7.0
webpack-cli (webpack-cli -> @webpack-cli/serve -> *webpack-cli*)
        * Was updated.
        * 4.7.2 => 4.10.0
colorette (webpack-cli -> *colorette*)
        * Was updated.
        * 1.2.2 => 2.0.19
execa (webpack-cli -> *execa*)
        * Was removed.
        * Had 9 direct dependencies (not listed here).
fastest-levenshtein (webpack-cli -> *fastest-levenshtein*)
        * Was updated.
        * 1.0.12 => 1.0.16
import-local (webpack-cli -> *import-local*)
        * Was updated.
        * 3.0.2 => 3.1.0
resolve (webpack-cli -> rechoir -> *resolve*)
        * Was updated.
        * 1.20.0 => 1.22.1
supports-preserve-symlinks-flag (webpack-cli -> rechoir -> resolve -> *supports-preserve-symlinks-flag*)
        * Was added.
        * Has 0 direct dependencies (not listed here).
is-core-module (webpack-cli -> rechoir -> resolve -> *is-core-module*)
        * Was updated.
        * 2.5.0 => 2.11.0
v8-compile-cache (webpack-cli -> *v8-compile-cache*)
        * Was removed.
        * Had 0 direct dependencies (not listed here).
webpack (webpack-cli -> *webpack*)
        * Was updated.
        * 5.47.0 => 5.75.0
webpack
        * Was updated.
        * 5.47.0 => 5.75.0
acorn-import-assertions (webpack -> *acorn-import-assertions*)
        * Was added.
        * Has 1 direct dependencies (not listed here).
json-parse-even-better-errors (webpack -> *json-parse-even-better-errors*)
        * Was added.
        * Has 0 direct dependencies (not listed here).
@types/eslint-scope (webpack -> *@types/eslint-scope*)
        * Was updated.
        * 3.7.1 => 3.7.4
@types/eslint (webpack -> @types/eslint-scope -> *@types/eslint*)
        * Was updated.
        * 7.28.0 => 8.21.1
@types/estree (webpack -> @types/eslint-scope -> @types/eslint -> *@types/estree*)
        * Was updated.
        * 0.0.50 => 0.0.51
@types/json-schema (webpack -> @types/eslint-scope -> @types/eslint -> *@types/json-schema*)
        * Was updated.
        * 7.0.8 => 7.0.11
@types/estree (webpack -> @types/eslint-scope -> *@types/estree*)
        * Was updated.
        * 0.0.50 => 0.0.51
@types/estree (webpack -> *@types/estree*)
        * Was updated.
        * 0.0.50 => 0.0.51
acorn (webpack -> *acorn*)
        * Was updated.
        * 8.4.1 => 8.8.2
browserslist (webpack -> *browserslist*)
        * Was updated.
        * 4.16.6 => 4.21.5
update-browserslist-db (webpack -> browserslist -> *update-browserslist-db*)
        * Was added.
        * Has 3 direct dependencies (not listed here).
caniuse-lite (webpack -> browserslist -> *caniuse-lite*)
        * Was updated.
        * 1.0.30001248 => 1.0.30001457
colorette (webpack -> browserslist -> *colorette*)
        * Was removed.
        * Had 0 direct dependencies (not listed here).
electron-to-chromium (webpack -> browserslist -> *electron-to-chromium*)
        * Was updated.
        * 1.3.790 => 1.4.308
escalade (webpack -> browserslist -> *escalade*)
        * Was removed.
        * Had 0 direct dependencies (not listed here).
node-releases (webpack -> browserslist -> *node-releases*)
        * Was updated.
        * 1.1.73 => 2.0.10
enhanced-resolve (webpack -> *enhanced-resolve*)
        * Was updated.
        * 5.8.2 => 5.12.0
es-module-lexer (webpack -> *es-module-lexer*)
        * Was updated.
        * 0.7.1 => 0.9.3
estraverse (webpack -> eslint-scope -> esrecurse -> *estraverse*)
        * Was updated.
        * 5.2.0 => 5.3.0
graceful-fs (webpack -> *graceful-fs*)
        * Was updated.
        * 4.2.6 => 4.2.10
json-parse-better-errors (webpack -> *json-parse-better-errors*)
        * Was removed.
        * Had 0 direct dependencies (not listed here).
loader-runner (webpack -> *loader-runner*)
        * Was updated.
        * 4.2.0 => 4.3.0
mime-types (webpack -> *mime-types*)
        * Was updated.
        * 2.1.32 => 2.1.35
mime-db (webpack -> mime-types -> *mime-db*)
        * Was updated.
        * 1.49.0 => 1.52.0
@types/json-schema (webpack -> schema-utils -> *@types/json-schema*)
        * Was updated.
        * 7.0.8 => 7.0.11
punycode (webpack -> schema-utils -> ajv -> uri-js -> *punycode*)
        * Was updated.
        * 2.1.1 => 2.3.0
tapable (webpack -> *tapable*)
        * Was updated.
        * 2.2.0 => 2.2.1
terser-webpack-plugin (webpack -> *terser-webpack-plugin*)
        * Was updated.
        * 5.1.4 => 5.3.6
@jridgewell/trace-mapping (webpack -> terser-webpack-plugin -> *@jridgewell/trace-mapping*)
        * Was added.
        * Has 2 direct dependencies (not listed here).
jest-worker (webpack -> terser-webpack-plugin -> *jest-worker*)
        * Was updated.
        * 27.0.6 => 27.5.1
@types/node (webpack -> terser-webpack-plugin -> jest-worker -> *@types/node*)
        * Was updated.
        * 16.4.6 => 18.14.0
p-limit (webpack -> terser-webpack-plugin -> *p-limit*)
        * Was removed.
        * Had 1 direct dependencies (not listed here).
serialize-javascript (webpack -> terser-webpack-plugin -> *serialize-javascript*)
        * Was updated.
        * 6.0.0 => 6.0.1
source-map (webpack -> terser-webpack-plugin -> *source-map*)
        * Was removed.
        * Had 0 direct dependencies (not listed here).
terser (webpack -> terser-webpack-plugin -> *terser*)
        * Was updated.
        * 5.7.1 => 5.16.4
@jridgewell/source-map (webpack -> terser-webpack-plugin -> terser -> *@jridgewell/source-map*)
        * Was added.
        * Has 2 direct dependencies (not listed here).
acorn (webpack -> terser-webpack-plugin -> terser -> *acorn*)
        * Was added.
        * Has 0 direct dependencies (not listed here).
source-map-support (webpack -> terser-webpack-plugin -> terser -> *source-map-support*)
        * Was updated.
        * 0.5.19 => 0.5.21
buffer-from (webpack -> terser-webpack-plugin -> terser -> source-map-support -> *buffer-from*)
        * Was updated.
        * 1.1.1 => 1.1.2
source-map (webpack -> terser-webpack-plugin -> terser -> *source-map*)
        * Was removed.
        * Had 0 direct dependencies (not listed here).
webpack (webpack -> terser-webpack-plugin -> *webpack*)
        * Was updated.
        * 5.47.0 => 5.75.0
watchpack (webpack -> *watchpack*)
        * Was updated.
        * 2.2.0 => 2.4.0
graceful-fs (webpack -> watchpack -> *graceful-fs*)
        * Was updated.
        * 4.2.6 => 4.2.10
webpack-sources (webpack -> *webpack-sources*)
        * Was updated.
        * 3.0.4 => 3.2.3
```

### CODE REVIEW

**Review by anne-gropler — DISMISSED** [review]
Removed code is always nice :D
Tested locally by using this version in my platform, installed and worked nice.

**Comment by adi64** [comment]
Shouldn't we bump the `version` field in the `package.json`?

**Comment by UniquePanda** [comment]
> Shouldn't we bump the `version` field in the `package.json`?

Yes, for whatever reason I completely forgot that, although it was the main prupose for opening this PR 🤦  
It's done now :D

**Review by anne-gropler — APPROVED** [review]
nice, now that the version number was actually bumped :D

**Pull request merged**
